import NavBar from "@/componets/NavBar.js";
import { Inter } from "next/font/google";
import '@/styles/globals.css'; // Importing global CSS styles, including Tailwind CSS

import { ToastContainer, toast } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// app/layout.js

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Weather App</title>
        <meta name="description" content="Simple Weather App using Next.js" />
      </head>
      <body className="bg-gray-100 text-gray-800">
        <NavBar/> {/* Include the NavBar component */}
        <ToastContainer /> {/* Add the ToastContainer */}
        {children}
      </body>
    </html>
  );
}

